version: "3"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - /tmp:/sql
    networks:
      - network
    ports:
      - 3306
    environment:
      MYSQL_USER: "admin"
      MYSQL_ROOT_PASSWORD: "welcome"
      MYSQL_PASSWORD: "welcome"
    restart: always
  payments:
    image: candy-shop
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 8081
    environment:
      MYSQL_HOST: "mysql"
    restart: always
  lb:
    image: eeacms/haproxy
    depends_on:
      - payments
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "payments"
      BACKENDS_PORT: "8081"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network
volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge