version: "3"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - /tmp:/sql
    networks:
      - network
    ports:
      - 3306
    environment:
      MYSQL_USER: "admin"
      MYSQL_ROOT_PASSWORD: "welcome"
      MYSQL_PASSWORD: "welcome"
    restart: always
  payments:
    image: candy-shop
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 8080
    environment:
      MYSQL_HOST: "mysql"
    restart: always

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge